{
  "Uuid": "3c9d0464-8643-5ffe-96e5-ab1769818209",
  "IsCustomNode": false,
  "Description": "",
  "Name": "1-3_Sphere",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleSlider, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "MaximumValue": 100.0,
      "MinimumValue": 0.0,
      "StepValue": 0.1,
      "InputValue": 72.5,
      "Id": "7622a08c0a074a948352f6f349c77e33",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "1f19f4ef2bad49dbbed2a443c5adee5c",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "数値を生成するスライダ。"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Sphere.ByCenterPointRadius@Autodesk.DesignScript.Geometry.Point,double",
      "Id": "6e992bd6f1324531abbf526ca3676e7c",
      "Inputs": [
        {
          "Id": "b0383c40926341fe914258fc50469702",
          "Name": "centerPoint",
          "Description": "Point\n既定値 : Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f164a8d25a644becafcf2f30da6c382e",
          "Name": "radius",
          "Description": "double\n既定値 : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "118ea7b7f205409a87b658a0ba9322c7",
          "Name": "Sphere",
          "Description": "Sphere",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "入力された点を中心とし、指定された半径を持つソリッド球体を作成します。\n\nSphere.ByCenterPointRadius (centerPoint: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0), radius: double = 1): Sphere"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "b012b7d00fcd4d3d91345a4162273a0d",
      "Inputs": [
        {
          "Id": "81de4c54f8924458a0384af4864ebe98",
          "Name": "x",
          "Description": "X coordinate\n\ndouble\n既定値 : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "c42039af59dc48d89ffc10fa40f356c9",
          "Name": "y",
          "Description": "Y coordinate\n\ndouble\n既定値 : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "c8ad058eec434f93bb3992d96c60dc65",
          "Name": "z",
          "Description": "Z coordinate\n\ndouble\n既定値 : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "7559abc30f264164ab723c5ae4564919",
          "Name": "Point",
          "Description": "Point created by coordinates",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "指定された 3 つのデカルト座標を使用して、点を作成します。\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    }
  ],
  "Connectors": [
    {
      "Start": "1f19f4ef2bad49dbbed2a443c5adee5c",
      "End": "f164a8d25a644becafcf2f30da6c382e",
      "Id": "ff853492bce64c5d9b563aa555cfb844"
    },
    {
      "Start": "7559abc30f264164ab723c5ae4564919",
      "End": "b0383c40926341fe914258fc50469702",
      "Id": "adbcac96abb645e59286c9de9975228c"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "Thumbnail": null,
  "GraphDocumentationURL": null,
  "ExtensionWorkspaceData": [
    {
      "ExtensionGuid": "28992e1d-abb9-417f-8b1b-05e053bee670",
      "Name": "Properties",
      "Version": "2.12",
      "Data": {}
    },
    {
      "ExtensionGuid": "DFBD9CC0-DB40-457A-939E-8C8555555A9D",
      "Name": "Generative Design",
      "Version": "1.10",
      "Data": {}
    }
  ],
  "Author": "None provided",
  "Linting": {
    "activeLinter": "なし",
    "activeLinterId": "7b75fb44-43fd-4631-a878-29f4d5d8399a",
    "warningCount": 0,
    "errorCount": 0
  },
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.12.0.5650",
      "RunType": "Automatic",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "背景プレビュー",
      "EyeX": -283.21084594726563,
      "EyeY": -280.42367553710938,
      "EyeZ": 340.52676391601563,
      "LookX": 293.69638061523438,
      "LookY": 301.03475952148438,
      "LookZ": -440.55758666992188,
      "UpX": -0.3711584210395813,
      "UpY": 0.74314570426940918,
      "UpZ": 0.55675488710403442
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Number Slider",
        "Id": "7622a08c0a074a948352f6f349c77e33",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 22808.421182214712,
        "Y": -16667.671014004572
      },
      {
        "ShowGeometry": true,
        "Name": "Sphere.ByCenterPointRadius",
        "Id": "6e992bd6f1324531abbf526ca3676e7c",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 23208.425720207022,
        "Y": -16752.823184321427
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "b012b7d00fcd4d3d91345a4162273a0d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 22951.788876431878,
        "Y": -16811.507232767151
      }
    ],
    "Annotations": [],
    "X": -13376.891225543539,
    "Y": 10165.580148385168,
    "Zoom": 0.59399634733377027
  }
}